# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

default_platform(:ios)

platform :ios do
  desc "Testing App"
  lane :tests do
  run_tests(workspace: "SpaceDash.xcworkspace",devices: ["iPhone 11", "iPhone 8","iPad Pro (12.9-inch) (3rd generation)"],scheme: "SpaceDash")
end
lane :beta do
  get_certificates
  get_provisioning_profile
  build_app(scheme: "SpaceDash")
  upload_to_testflight
end

lane :build_version do
  ensure_git_status_clean
  increment_build_number(xcodeproj: "SpaceDash.xcodeproj")
  commit_version_bump(xcodeproj: "SpaceDash.xcodeproj")
  add_git_tag( grouping: "fastlane-builds" )
  push_to_git_remote
end
end
