# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

default_platform(:ios)

platform :ios do
  desc "Testing App"
lane :tests do
  run_tests(workspace: "SpaceDash.xcworkspace",devices: ["iPhone 11", "iPhone 8","iPad Pro (12.9-inch) (3rd generation)"],scheme: "SpaceDash")
end

lane :beta do
  git_pull
  get_certificates
  get_provisioning_profile
  build_app(scheme: "SpaceDash")

  changelog = File.read("./changelog.txt") 
 
  upload_to_testflight(
   changelog: changelog, 
   distribute_external: true,
   groups: ["External Testers", "Unknown External Testers"] )
end

lane :build_version do
  ensure_git_status_clean
  increment_build_number(xcodeproj: "SpaceDash.xcodeproj")
  commit_version_bump(xcodeproj: "SpaceDash.xcodeproj")
  push_to_git_remote
end

lane :screenshots do
 capture_screenshots(scheme: "FastlaneSnapshots")
 frameit
end

lane :release do
 
 capture_screenshots(scheme: "FastlaneSnapshots")
 frameit
 get_certificates
 get_provisioning_profile
 build_app(scheme: "SpaceDash")
  
 upload_to_app_store(force: true, overwrite_screenshots: true)
 
 set_changelog

 deliver(
    submit_for_review: false,
    automatic_release: true,
    force: true, # Skip HTMl report verification
    skip_metadata: false,
    skip_screenshots: true,
    skip_binary_upload: true,
    submission_information: {
      export_compliance_uses_encryption: false,
      add_id_info_uses_idfa: false
   }
  ) 
end

lane :minor_version do
  increment_version_number_in_plist(
  bump_type:'minor',
  version_source:'appstore',
  target:'SpaceDash'
)
  commit_version_bump(force: true, xcodeproj: "SpaceDash.xcodeproj")
  push_to_git_remote
end
end
